### ISSUE TITLE
"MyHelp" error message

### ISSUE THREAD

**Issue by forespoken** [inadvertently/Blame-Discord-Bot#6]
![image](https://github.com/inadvertently/Blame-Discord-Bot/assets/166189203/cda9433e-8240-441a-9c1e-99a114cc3d56)

copied everything correctly and even tried so many workarounds and nothing seemed to work. still always getting message above. please let me know how to fix!

**Comment by inadvertently** [comment]
It is a class within the Core file. If it raises an attribute error, you most likely deleted the class and it is no longer present when trying to access it.

**Comment by forespoken** [comment]
> It is a class within the Core file. If it raises an attribute error, you most likely deleted the class and it is no longer present when trying to access it.

yea i fixed that. now I'm getting "discord.errors.LoginFailure: Improper token has been passed" how do i put the token correctly without it saying this. I've tried like 5 different ways of doing so

![Screenshot 2024-04-09 152239](https://github.com/inadvertently/Blame-Discord-Bot/assets/166189203/5887590b-bff5-44cd-a063-fe73a35780f9)

**Comment by inadvertently** [comment]
> > It is a class within the Core file. If it raises an attribute error, you most likely deleted the class and it is no longer present when trying to access it.
> 
> 
> 
> yea i fixed that. now I'm getting "discord.errors.LoginFailure: Improper token has been passed" how do i put the token correctly without it saying this. I've tried like 5 different ways of doing so
> 
> 
> 
> ![Screenshot 2024-04-09 152239](https://github.com/inadvertently/Blame-Discord-Bot/assets/166189203/5887590b-bff5-44cd-a063-fe73a35780f9)
> 
> 

Your token should be defined within the env file "DISCORD_TOKEN". Make sure you didn't delete that file as you'll need it for the entire bot. If you still can't figure it out just make the token a variable within the main file for simplicity. ``token = "your token"``

**Comment by forespoken** [comment]
> > > It is a class within the Core file. If it raises an attribute error, you most likely deleted the class and it is no longer present when trying to access it.
> > 
> > 
> > yea i fixed that. now I'm getting "discord.errors.LoginFailure: Improper token has been passed" how do i put the token correctly without it saying this. I've tried like 5 different ways of doing so
> > ![Screenshot 2024-04-09 152239](https://private-user-images.githubusercontent.com/166189203/320976730-5887590b-bff5-44cd-a063-fe73a35780f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzE3NDQsIm5iZiI6MTcxMjczMTQ0NCwicGF0aCI6Ii8xNjYxODkyMDMvMzIwOTc2NzMwLTU4ODc1OTBiLWJmZjUtNDRjZC1hMDYzLWZlNzNhMzU3ODBmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNjQ0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzlmMmYxODVjMmNlOTJkYjI1OGY1ZTA3YzA2OWM0NjY0NzRmMTBjNTllMzZkN2UyNmRlZjNhZDg1M2QxYjE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6oBHm3ywK20-IGIFoiItKH8C9G-pnt7k1rP-R4Z-_74)
> 
> Your token should be defined within the env file "DISCORD_TOKEN". Make sure you didn't delete that file as you'll need it for the entire bot. If you still can't figure it out just make the token a variable within the main file for simplicity. `token = "your token"`

![image](https://github.com/inadvertently/Blame-Discord-Bot/assets/166189203/9e6fa84f-0b28-46cb-8bac-9212e5591a3d)

Now I'm getting this circular import. every time i fix something, another thing breaks.

**Comment by inadvertently** [comment]
That isn't from blame.
